name: Semver check

on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: The tag to check if stable
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  semver-stable-check:
    runs-on: ubuntu-latest
    outputs:
      is_stable: ${{ steps.version.outputs.is_stable }}
    steps:
      - name: Make sure tag is a stable semver version
        id: version
        run: |
          regex="[0-9]+\.[0-9]+\.[0-9]+$"
          if [[ ${{ inputs.tag_version }} =~ $regex ]]; then
            echo ::set-output name=is_stable::true
          else
            echo ::set-output name=is_stable::false
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: semver-stable-check
    if: ${{ needs.semver-stable-check.outputs.is_stable == 'true' }}
    steps:
      - name: Hello world
        run: echo "Hello world"
